/**
 * Generate the spiral border strip used as `border-image` on project tiles.
 *
 *   node scripts/spiral-border.mjs > src/styles/spiral-border.css
 *
 * Draws one tile of a seamless horizontal band of small star-spirals, using the
 * same generator as the old /work star view (pixel-snapped, star-modulated
 * radius). Emitted as an inlined SVG data URI so there's no extra request and
 * the colour can be swapped in one place.
 */

const TILE = 96; // strip repeats every 96px
const BAND = 16; // strip height; the border is 8px, so this renders at 2x

// NB: no pixel-snapping here. The star view snapped to a 3px grid, but at this
// size a whole spiral spans ~6px — snapping collapses every point onto the
// centre and the figure vanishes. Sub-pixel coordinates are the point.
const pix = (n) => n;

function starRadius(baseR, angle, points, amount) {
  const star = Math.pow(Math.abs(Math.cos((angle * points) / 2)), 0.4);
  return baseR * (1 - amount + amount * (0.42 + 0.58 * star));
}

/** One spiral as an SVG path. Same maths as the star view, scaled to the band. */
function spiral({ cx, cy, arms, turns, tight, points, starAmt, dir, scale = 1 }) {
  const steps = Math.floor(turns * 36);
  const paths = [];
  for (let arm = 0; arm < arms; arm++) {
    const armOffset = (arm / arms) * Math.PI * 2;
    let d = '';
    for (let j = 0; j <= steps; j++) {
      const angle = dir * (j / 36) * Math.PI * 2 + armOffset;
      // grow to `tight` (in px) across the whole arm, so the figure fills the band
      const r = starRadius((j / steps) * tight * scale, angle, points, starAmt);
      const x = pix(cx + Math.cos(angle) * r);
      const y = pix(cy + Math.sin(angle) * r);
      d += `${j === 0 ? 'M' : 'L'}${x.toFixed(1)} ${y.toFixed(1)}`;
    }
    paths.push(d);
  }
  return paths;
}

/**
 * A family of bands, so different parts of the site aren't wearing the same
 * ornament. Each is the same generator at different settings:
 *
 *   tangle  dense, mixed sizes — the project tiles' frame
 *   sparse  few small figures, wide gaps — page furniture (header, footer)
 *   coil    tight single-arm curls, evenly spaced — section rules
 *   bloom   large open rosettes — a heavier accent for one-off use
 */
const BANDS = {
  tangle: [
    { cx: 12, cy: 8, arms: 2, turns: 1.6, tight: 6.5, points: 5, starAmt: 0.55, dir: 1 },
    { cx: 36, cy: 8, arms: 1, turns: 2.2, tight: 5.2, points: 4, starAmt: 0.5, dir: -1 },
    { cx: 60, cy: 8, arms: 3, turns: 1.4, tight: 6.8, points: 6, starAmt: 0.6, dir: 1 },
    { cx: 84, cy: 8, arms: 1, turns: 2.6, tight: 4.6, points: 5, starAmt: 0.45, dir: -1 },
  ],
  sparse: [
    { cx: 24, cy: 8, arms: 1, turns: 1.8, tight: 4.4, points: 5, starAmt: 0.5, dir: 1 },
    { cx: 72, cy: 8, arms: 1, turns: 1.8, tight: 4.4, points: 5, starAmt: 0.5, dir: -1 },
  ],
  coil: [
    { cx: 16, cy: 8, arms: 1, turns: 2.8, tight: 3.6, points: 3, starAmt: 0.3, dir: 1 },
    { cx: 48, cy: 8, arms: 1, turns: 2.8, tight: 3.6, points: 3, starAmt: 0.3, dir: -1 },
    { cx: 80, cy: 8, arms: 1, turns: 2.8, tight: 3.6, points: 3, starAmt: 0.3, dir: 1 },
  ],
  bloom: [
    { cx: 24, cy: 8, arms: 3, turns: 1.2, tight: 7.2, points: 8, starAmt: 0.7, dir: 1 },
    { cx: 72, cy: 8, arms: 3, turns: 1.2, tight: 7.2, points: 8, starAmt: 0.7, dir: -1 },
  ],
};

const wrap = (w, h, paths) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" ` +
  `viewBox="0 0 ${w} ${h}">` +
  `<g fill="none" stroke="#ff9fe5" stroke-width="0.7" stroke-linejoin="round">` +
  paths +
  `</g></svg>`;

const draw = (figs) => figs.flatMap(spiral).map((d) => `<path d="${d}"/>`).join('');

// base64 rather than percent-encoding: the raw markup contains quotes, spaces
// and angle brackets that browsers parse inconsistently inside a url() token.
const uri = (svg) => `url("data:image/svg+xml;base64,${Buffer.from(svg, 'utf8').toString('base64')}")`;

let out = '/* generated by scripts/spiral-border.mjs — do not edit by hand */\n:root {\n';

for (const [name, figs] of Object.entries(BANDS)) {
  const h = wrap(TILE, BAND, draw(figs));
  // vertical variant: figures laid out down the strip. (Rotating the horizontal
  // one via a transform pushes the paths outside the viewBox and renders nothing.)
  const v = wrap(BAND, TILE, draw(figs.map((f) => ({ ...f, cx: 8, cy: f.cx }))));
  out += `  --spiral-${name}:   ${uri(h)};\n`;
  out += `  --spiral-${name}-v: ${uri(v)};\n`;
}

// the tile frame's default stays available under the original names
out += `  --spiral-band:   var(--spiral-tangle);\n`;
out += `  --spiral-band-v: var(--spiral-tangle-v);\n`;
out += '}\n';

process.stdout.write(out);
